name: 'Setup Bun Runtime'
description: 'Setup Bun Runtime'
author: 'Anton Golub'
inputs:
  bun-version:
    description: 'Version Spec of the version to use. Examples: 0.0.77, 0.1.2, >=0.1'
    required: false
  version:
    description: 'Alias for bun-version option'
    required: false
  bun-repo:
    description: 'GitHub release stream to use. Defaults to: Jarred-Sumner/bun-releases-for-updater'
    required: false

runs:
  using: 'node16'
  main: 'target/main/index.js'
  post: 'target/post/index.js'
  post-if: success()
