name: 'Setup Bun Runtime'
description: 'Setup Bun Runtime'
author: 'Anton Golub'
inputs:
  bun-version:
    description: 'Version Spec of the version to use. Examples: 0.0.77, 0.1.2, >=0.1'
    required: false
  bun-repo:
    description: 'GitHub release stream to use. Defaults to: Jarred-Sumner/bun-releases-for-updater'
    required: false
  version:
    description: 'Alias for bun-version option'
    required: false
  cache:
    description: 'Enable cross-job installed modules caching. Default is false'
    required: false
  cache-bin:
    description: 'Enable cross-job installed bun binaries caching. Default is false'
    required: false
  bun-config:
    description: 'Override bunfig.toml file. JSON string as input'
    required: false
  config:
    description: 'bun-config option alias'
    required: false
  token:
    description: 'GitHub PAT token to use'
    default: ${{ github.token }}
    required: false

outputs:
  cache-hit:
    description: 'A boolean value to indicate if a module cache was hit'
  bun-version:
    description: 'The installed bun version'
  error:
    description: 'The error message if any'

runs:
  using: 'node20'
  main: 'target/main/index.js'
  post: 'target/post/index.js'
  post-if: success()
