name: integration-test
on: [push]
jobs:
  action-test:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest ]

    runs-on: ${{ matrix.os }}

    name: Action test (${{ matrix.os }})
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Setup Bun
        uses: ./

      - name: Run script
        run: bun -v
